distro_ascii: auto
disable_amdgpu_ids_warning: false
modules:
  - name: distribution
  - name: hostname
  - name: kernel
  - name: packages
  - name: shell
  - name: init_system
  - name: motherboard
  - name: cpus
  - name: gpus
  - name: memory
  - name: partitions
  - name: local_ip
  - name: de_wm
  - name: monitors
