distro_ascii: auto
modules:
  - name: distribution
  - name: hostname
  - name: kernel
  - name: packages
  - name: shell
  - name: init
  - name: motherboard
  - name: cpu
  - name: gpus
  - name: memory
  - name: partitions
  - name: local_ip
  - name: de_wm
  - name: monitors
